import { FilterField } from "../../common/FilterBar";

export const reportFilterFields: FilterField[] = [
  {
    key: "search",
    label: "Search",
    type: "text",
    placeholder: "Report name or generated by",
  },
  {
    key: "reportType",
    label: "Report Type",
    type: "select",
    options: [
      { label: "Employee", value: "Employee" },
      { label: "Attendance", value: "Attendance" },
      { label: "Leave", value: "Leave" },
      { label: "Payroll", value: "Payroll" },
    ],
  },
  {
    key: "status",
    label: "Status",
    type: "select",
    options: [
      { label: "Completed", value: "Completed" },
      { label: "Processing", value: "Processing" },
    ],
  },
];
