"use client";

import {
  Chip,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@mui/material";

import { reports } from "../../constants/reports";

const getStatusColor = (
  status: string
): "success" | "warning" => {
  return status === "Completed" ? "success" : "warning";
};

export default function RecentReports() {
  return (
    <TableContainer component={Paper} sx={{ borderRadius: 3 }}>
      <Table>
        <TableHead>
          <TableRow>
            <TableCell>Report</TableCell>
            <TableCell>Type</TableCell>
            <TableCell>Generated By</TableCell>
            <TableCell>Date</TableCell>
            <TableCell>Status</TableCell>
          </TableRow>
        </TableHead>

        <TableBody>
          {reports.map((report) => (
            <TableRow key={report.id}>
              <TableCell>{report.reportName}</TableCell>
              <TableCell>{report.reportType}</TableCell>
              <TableCell>{report.generatedBy}</TableCell>
              <TableCell>{report.generatedOn}</TableCell>
              <TableCell>
                <Chip
                  label={report.status}
                  color={getStatusColor(report.status)}
                  size="small"
                />
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
}