"use client";

import { Grid, MenuItem, TextField } from "@mui/material";

import { ReportRecord } from "../../redux/slices/reportSlice";

interface ReportFormProps {
  formData: ReportRecord;
  onChange: (
    field: keyof ReportRecord,
    value: string | number
  ) => void;
}

const reportTypes: ReportRecord["reportType"][] = [
  "Employee",
  "Attendance",
  "Leave",
  "Payroll",
];

const statuses: ReportRecord["status"][] = [
  "Completed",
  "Processing",
];

export default function ReportForm({
  formData,
  onChange,
}: ReportFormProps) {
  return (
    <Grid container spacing={2} sx={{ mt: 1 }}>
      <Grid size={{ xs: 12 }}>
        <TextField
          fullWidth
          label="Report Name"
          value={formData.reportName}
          onChange={(e) =>
            onChange("reportName", e.target.value)
          }
        />
      </Grid>

      <Grid size={{ xs: 12, md: 6 }}>
        <TextField
          select
          fullWidth
          label="Report Type"
          value={formData.reportType}
          onChange={(e) =>
            onChange(
              "reportType",
              e.target.value as ReportRecord["reportType"]
            )
          }
        >
          {reportTypes.map((reportType) => (
            <MenuItem key={reportType} value={reportType}>
              {reportType}
            </MenuItem>
          ))}
        </TextField>
      </Grid>

      <Grid size={{ xs: 12, md: 6 }}>
        <TextField
          fullWidth
          label="Generated By"
          value={formData.generatedBy}
          onChange={(e) =>
            onChange("generatedBy", e.target.value)
          }
        />
      </Grid>

      <Grid size={{ xs: 12, md: 6 }}>
        <TextField
          type="date"
          fullWidth
          label="Generated On"
          InputLabelProps={{ shrink: true }}
          value={formData.generatedOn}
          onChange={(e) =>
            onChange("generatedOn", e.target.value)
          }
        />
      </Grid>

      <Grid size={{ xs: 12, md: 6 }}>
        <TextField
          select
          fullWidth
          label="Status"
          value={formData.status}
          onChange={(e) =>
            onChange(
              "status",
              e.target.value as ReportRecord["status"]
            )
          }
        >
          {statuses.map((status) => (
            <MenuItem key={status} value={status}>
              {status}
            </MenuItem>
          ))}
        </TextField>
      </Grid>
    </Grid>
  );
}
